local Exploit;
if identifyexecutor then
	Exploit,Ver = identifyexecutor()
	if Ver then
		Exploit = Exploit..' '..tostring(Ver)
	end
else
	Exploit = secure_load and "Sentinel" or pebc_execute and "ProtoSmasher" or is_sirhurt_closure and "Sirhurt" or (syn and not is_sirhurt_closure and not isexecutorclosure) and "Synapse X" or KRNL_LOADED and "Krnl"
end

local request = request or http_request or (syn and syn.request) or (getgenv and getgenv().http and getgenv().http.request) or nil

function LoadScript()
	loadstring(game:HttpGet("https://raw.githubusercontent.com/HexerMaster1929/HexSS/stable/mainscript.lua"))()
	if (rconsoleclose) then
		rconsoleclose()
	elseif (rconsoledestroy) then
		rconsoledestroy()
	elseif (rconsolehide) then
		rconsolehide()
	end
	
end

if (rconsoleprint) then
	if Exploit == "ScriptWare" then --special loader for sw because there rconsole system and functions are different then normal rconsole
		
		--[[consolecreate()
		consoleprint("Checking\n",'white')
		wait(.2)
		consoleprint("Checking Executor Support\n","magenta")
		wait(2)
		consoleprint("SUCCESS\n","green")
		consoleprint("Executor: "..tostring(Exploit).."\n","magenta")
		wait(.2)
		consoleprint("Checking Function Support\n","magenta")
		consoleprint("Checking getgenv\n","magenta")]]
		LoadScript() -- to lazy to make loader for sw rn
		
	else
		rconsolename("HexSS BaseLoader")

		rconsoleprint("Checking\n")
		wait(.2)
		rconsoleprint('@@MAGENTA@@')
		rconsoleprint('Checking Executor Support\n')
		wait(2)
		rconsoleprint('@@LIGHT_GREEN@@')
		rconsoleprint('SUCCESS\n')
		rconsoleprint('Executor: '..tostring(Exploit)..'\n')
		wait(.2)
		rconsoleprint('@@MAGENTA@@')
		rconsoleprint('Checking Function Support (0/5)\n')
		rconsoleprint('Checking getgenv (1/5)\n')
		if (getgenv) then
			wait(math.random(0.2,3))
			rconsoleprint('@@LIGHT_GREEN@@')
			rconsoleprint('SUCCESS\n')
			rconsoleprint('@@MAGENTA@@')
			rconsoleprint('Checking Request (2/5)\n')
			if request ~= nil then
				wait(math.random(0.2,3))
				rconsoleprint('@@LIGHT_GREEN@@')
				rconsoleprint('SUCCESS\n')
				rconsoleprint('@@MAGENTA@@')
				rconsoleprint('Checking gethui (3/5)\n')
				if gethui or syn.protect_gui then
					wait(math.random(0.2,3))
					rconsoleprint('@@LIGHT_GREEN@@')
					rconsoleprint('SUCCESS\n')
					rconsoleprint('@@MAGENTA@@')
					rconsoleprint('Checking filesystem functions (4/5)\n')
					if (readfile) or (writefile) or (isfile) or (isfolder) or (writefolder) or (listfiles) then
						wait(math.random(0.2,3))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Tabs Module\n')
						wait(math.random(2,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Drag Module\n')
						wait(math.random(.3,2))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Filesystem Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading MSB Module\n')
						wait(math.random(.3,4))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Listing Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading UI Module\n')
						wait(math.random(.7,4))
						LoadScript()
					else
						wait(math.random(0.2,3))
						rconsoleprint('@@YELLOW@@')
						rconsoleprint('Your Executor Does Not Support filesystem functions, your added scripts and settings will not save!\n')
						wait(math.random(0.2,3))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Tabs Module\n')
						wait(math.random(2,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Drag Module\n')
						wait(math.random(.3,2))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Filesystem Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading MSB Module\n')
						wait(math.random(.3,4))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Listing Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading UI Module\n')
						wait(math.random(.7,4))
						LoadScript()
					end
				else
					wait(math.random(0.2,3))
					rconsoleprint('@@YELLOW@@')
					rconsoleprint('Your Executor Does Not Support gethui or syn.protect, Gui may be detected by any game anticheat\n')
					rconsoleprint('@@MAGENTA@@')
					rconsoleprint('Checking filesystem functions (5/5)\n')
					if (readfile) or (writefile) or (isfile) or (isfolder) or (writefolder) or (listfiles) then
						wait(math.random(0.2,3))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Tabs Module\n')
						wait(math.random(2,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Drag Module\n')
						wait(math.random(.3,2))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Filesystem Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading MSB Module\n')
						wait(math.random(.3,4))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Listing Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading UI Module\n')
						wait(math.random(.7,4))
						LoadScript()
					else
						wait(math.random(0.2,3))
						rconsoleprint('@@YELLOW@@')
						rconsoleprint('Your Executor Does Not Support filesystem functions, your added scripts and settings will not save!\n')
						wait(math.random(0.2,3))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Tabs Module\n')
						wait(math.random(2,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Drag Module\n')
						wait(math.random(.3,2))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Filesystem Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading MSB Module\n')
						wait(math.random(.3,4))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading Listing Module\n')
						wait(math.random(.3,7))
						rconsoleprint('@@LIGHT_GREEN@@')
						rconsoleprint('SUCCESS\n')
						rconsoleprint('@@MAGENTA@@')
						rconsoleprint('Loading UI Module\n')
						wait(math.random(.7,4))
						LoadScript()
					end
				end
			else
				wait(math.random(0.2,3))
				rconsoleprint('@@RED@@')
				rconsoleprint('Your Executor Does Not Support requests, Aborting Launching HexSS\n')
			end
		else
			wait(math.random(0.2,3))
			rconsoleprint('@@RED@@')
			rconsoleprint('Your Executor Does Not Support getgenv, Aborting Launching HexSS\n')
		end

	end
else
	error("Loader Requires Rconsole")
end


